import React,{useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{LayoutDashboard,ShoppingBag,Package,Users,ShoppingCart,ReceiptText,Truck,Settings,Search,Bell,Menu,ChevronDown,ArrowUpRight,IndianRupee,Clock3,AlertTriangle,Plus,MoreHorizontal,CheckCircle2,XCircle,Minus}from'lucide-react';import'./styles.css';

type Tab='Overview'|'Orders'|'Inventory'|'Abandoned carts'|'Customers'|'Invoices'|'Delivery slots'|'Settings';
const nav:[Tab,any][]=[['Overview',LayoutDashboard],['Orders',ShoppingBag],['Inventory',Package],['Abandoned carts',ShoppingCart],['Customers',Users],['Invoices',ReceiptText],['Delivery slots',Truck],['Settings',Settings]];
const initialProducts=[['JWM-CHK-001','Classic Chicken Curry Cut','Chicken','₹179',32],['JWM-CHK-002','Chicken Breast Boneless','Chicken','₹229',18],['JWM-MUT-001','Premium Mutton Chops','Mutton','₹449',9],['JWM-FSH-001','Fresh Whole Rohu','Fish & Seafood','₹199',14],['JWM-SEA-001','Whole Freshwater Prawns','Fish & Seafood','₹249',6],['JWM-EGG-001','Farm Fresh Eggs','Eggs','₹109',45],['JWM-RTC-001','Tandoori Chicken Tikka','Ready to Cook','₹239',11],['JWM-CMB-001','Family Curry Combo','Combos','₹249',8]] as const;
const orders=[['JWM-1028','Ananya Singh','₹628','7–9 PM','New'],['JWM-1027','Rohit Kumar','₹449','4–6 PM','Confirmed'],['JWM-1026','Nisha Verma','₹782','12–3 PM','Preparing'],['JWM-1025','Aman Gupta','₹358','9–11 AM','Out for delivery'],['JWM-1024','Priya Sinha','₹578','12–3 PM','Delivered']];
const carts=[['Riya Sharma','98765 •••12','₹428','18 min ago'],['Amit Kumar','91234 •••89','₹699','42 min ago'],['Neha Singh','98351 •••44','₹249','1 hr ago'],['Guest user','834003','₹578','3 hrs ago']];
const customers=[['Ananya Singh','Verified','3 orders','₹1,728'],['Rohit Kumar','Verified','1 order','₹449'],['Nisha Verma','Pending email','2 orders','₹1,106'],['Aman Gupta','Verified','4 orders','₹2,084']];
function App(){const[tab,setTab]=useState<Tab>('Overview');const[mobile,setMobile]=useState(false);const[stocks,setStocks]=useState<Record<string,number>>(Object.fromEntries(initialProducts.map(p=>[p[0],p[4]])));const low=Object.values(stocks).filter(x=>x<10).length;const adjust=(sku:string,n:number)=>setStocks(s=>({...s,[sku]:Math.max(0,s[sku]+n)}));return <div className="shell">
<aside className={mobile?'open':''}><div className="logo"><span>J</span><div><b>JAB<span>WE</span>MEAT<sup>™</sup></b><small>ADMIN CONSOLE</small></div></div><nav>{nav.map(([name,Icon])=><button className={tab===name?'active':''} onClick={()=>{setTab(name);setMobile(false)}} key={name}><Icon/>{name}{name==='Orders'&&<i>4</i>}{name==='Abandoned carts'&&<i>12</i>}</button>)}</nav><div className="admin-user"><div>SM</div><p><b>Sita Mehra</b><small>Administrator</small></p><ChevronDown/></div></aside>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{tab}</h1><p>Sunday, 13 September 2026</p></div><label><Search/><input placeholder="Search orders, SKU, customers…"/></label><button className="bell"><Bell/><i/></button><button className="store">View store <ArrowUpRight/></button></header><section className="content">
{tab==='Overview'&&<><div className="welcome"><div><span>RANCHI OPERATIONS</span><h2>Good afternoon, Sita.</h2><p>Here’s what is happening with JabWeMeat today.</p></div><button><Plus/> Add product</button></div><div className="metrics"><Metric icon={ShoppingBag} label="Live orders" value="12" note="4 need confirmation" tone="green"/><Metric icon={IndianRupee} label="Today’s COD value" value="₹8,420" note="↑ 12.5% vs yesterday" tone="gold"/><Metric icon={Package} label="Active SKUs" value="8" note={`${low} low-stock items`} tone="blue"/><Metric icon={ShoppingCart} label="Abandoned carts" value="12" note="₹4,286 potential value" tone="rose"/></div><div className="grid"><Panel title="Live order pipeline" action="View all orders" onAction={()=>setTab('Orders')}><div className="pipeline">{[['New','4'],['Confirmed','2'],['Preparing','3'],['Out for delivery','3']].map(([a,b],i)=><div key={a}><span className={`dot d${i}`}/><p><b>{b}</b><small>{a}</small></p></div>)}</div><OrderTable compact/></Panel><Panel title="Attention needed" action="Manage inventory" onAction={()=>setTab('Inventory')}><div className="alerts"><div><AlertTriangle/><p><b>{low} products are running low</b><small>Review stock before the next slot opens.</small></p></div><div><Clock3/><p><b>7–9 PM slot at 78%</b><small>11 of 14 order positions reserved.</small></p></div><div><ShoppingCart/><p><b>₹4,286 in abandoned carts</b><small>Recovery messaging is activation-ready.</small></p></div></div></Panel></div></>}
{tab==='Orders'&&<Page title="Orders" sub="Confirm, prepare, dispatch and complete COD orders."><OrderTable/></Page>}
{tab==='Inventory'&&<Page title="Products & inventory" sub="Prototype controls—changes reset when this preview reloads."><div className="table-wrap"><table><thead><tr><th>SKU / Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{initialProducts.map(p=><tr key={p[0]}><td><b>{p[1]}</b><small>{p[0]}</small></td><td>{p[2]}</td><td><b>{p[3]}</b></td><td><div className="stepper"><button onClick={()=>adjust(p[0],-1)}><Minus/></button><span>{stocks[p[0]]}</span><button onClick={()=>adjust(p[0],1)}><Plus/></button></div></td><td><Status value={stocks[p[0]]===0?'Out of stock':stocks[p[0]]<10?'Low stock':'In stock'}/></td><td><MoreHorizontal/></td></tr>)}</tbody></table></div></Page>}
{tab==='Abandoned carts'&&<Page title="Abandoned carts" sub="Review incomplete baskets and prepare recovery activity."><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Contact / PIN</th><th>Cart value</th><th>Last activity</th><th>Recovery</th></tr></thead><tbody>{carts.map(c=><tr><td><b>{c[0]}</b></td><td>{c[1]}</td><td><b>{c[2]}</b></td><td>{c[3]}</td><td><button className="outline">View cart</button></td></tr>)}</tbody></table></div></Page>}
{tab==='Customers'&&<Page title="Customers" sub="Profiles, verification and order history."><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Verification</th><th>Order history</th><th>Lifetime value</th></tr></thead><tbody>{customers.map(c=><tr><td><b>{c[0]}</b></td><td><Status value={c[1]}/></td><td>{c[2]}</td><td><b>{c[3]}</b></td></tr>)}</tbody></table></div></Page>}
{!['Overview','Orders','Inventory','Abandoned carts','Customers'].includes(tab)&&<Page title={tab} sub="This module is prepared for the backend implementation phase."><div className="empty"><Package/><h3>{tab} module</h3><p>The production database and workflow controls will appear here.</p><button>Configure module</button></div></Page>}
</section></main></div>}
const Metric=({icon:Icon,label,value,note,tone}:any)=><div className="metric"><span className={tone}><Icon/></span><p><small>{label}</small><b>{value}</b><i>{note}</i></p></div>;
const Panel=({title,action,onAction,children}:any)=><article className="panel"><div className="panel-head"><h3>{title}</h3><button onClick={onAction}>{action}<ArrowUpRight/></button></div>{children}</article>;
const Page=({title,sub,children}:any)=><><div className="page-title"><div><h2>{title}</h2><p>{sub}</p></div><button><Plus/> New</button></div>{children}</>;
const Status=({value}:any)=><span className={'status '+value.toLowerCase().replaceAll(' ','-')}>{['Delivered','Verified','In stock'].includes(value)?<CheckCircle2/>:['Out of stock'].includes(value)?<XCircle/>:<Clock3/>}{value}</span>;
const OrderTable=({compact=false}:any)=><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Value</th><th>Slot</th><th>Status</th></tr></thead><tbody>{orders.slice(0,compact?4:orders.length).map(o=><tr key={o[0]}><td><b>{o[0]}</b></td><td>{o[1]}</td><td><b>{o[2]}</b></td><td>{o[3]}</td><td><Status value={o[4]}/></td></tr>)}</tbody></table></div>;
createRoot(document.getElementById('root')!).render(<App/>);
