import type { Product } from './types';
export const PRODUCTS: Product[] = [
 {id:'p1',sku:'JWM-CHK-001',name:'Classic Chicken Curry Cut',category:'Chicken',description:'Fresh skinless curry pieces, cleaned and ready to cook.',weight:'500 g',servings:'3–4',price:179,mrp:209,stock:32,icon:'🍗',featured:true,attributes:['skinless'],cutTypes:['curry cut','small pieces'],recommendation:'Pair with Family Curry Combo',variants:[{weight:'250 g',price:99,mrp:119,stock:24},{weight:'500 g',price:179,mrp:209,stock:32},{weight:'1 kg',price:329,mrp:379,stock:18}]},
 {id:'p2',sku:'JWM-CHK-002',name:'Chicken Breast Boneless',category:'Chicken',description:'Lean, tender cuts for grills, curries and meal prep.',weight:'450 g',servings:'2–3',price:229,mrp:259,stock:18,icon:'🥩',featured:true,attributes:['boneless','skinless'],cutTypes:['fillet','cubes'],recommendation:'Great with Tandoori Chicken Tikka',variants:[{weight:'250 g',price:139,mrp:159,stock:26},{weight:'500 g',price:249,mrp:289,stock:18},{weight:'1 kg',price:459,mrp:519,stock:9}]},
 {id:'p3',sku:'JWM-MUT-001',name:'Premium Mutton Chops',category:'Mutton',description:'Meaty bone-in chops selected for grills and rich home-style curries.',weight:'500 g',servings:'3–4',price:449,mrp:499,stock:9,icon:'🍖',featured:true,attributes:['bone-in'],cutTypes:['chops','curry cut'],recommendation:'Add fresh Rohu for a feast',variants:[{weight:'250 g',price:239,mrp:269,stock:12},{weight:'500 g',price:449,mrp:499,stock:9},{weight:'1 kg',price:849,mrp:949,stock:4}]},
 {id:'p4',sku:'JWM-FSH-001',name:'Fresh Whole Rohu',category:'Fish & Seafood',description:'Fresh Rohu with cleaning and cut options for your kitchen.',weight:'Approx. 1 kg',servings:'4–5',price:199,mrp:229,stock:14,icon:'🐟',attributes:[],cutTypes:['whole','steaks','curry cut'],recommendation:'Complete the meal with chicken curry cut',variants:[{weight:'250 g',price:59,mrp:69,stock:22},{weight:'500 g',price:109,mrp:129,stock:19},{weight:'1 kg',price:199,mrp:229,stock:14}]},
 {id:'p5',sku:'JWM-SEA-001',name:'Whole Freshwater Prawns',category:'Fish & Seafood',description:'Fresh whole prawns suitable for curries, fries and quick starters.',weight:'250 g',servings:'2',price:249,mrp:289,stock:6,icon:'🦐',attributes:[],cutTypes:['whole','cleaned'],recommendation:'Try with Family Curry Combo',variants:[{weight:'250 g',price:249,mrp:289,stock:6},{weight:'500 g',price:469,mrp:529,stock:3},{weight:'1 kg',price:899,mrp:999,stock:0}]},
 {id:'p6',sku:'JWM-EGG-001',name:'Farm Fresh Eggs',category:'Eggs',description:'Clean, carefully packed everyday protein.',weight:'Pack of 12',servings:'6',price:109,mrp:119,stock:45,icon:'🥚',attributes:[],cutTypes:['pack'],recommendation:'Add to Chicken Curry Cut',variants:[{weight:'Pack of 6',price:59,mrp:65,stock:40},{weight:'Pack of 12',price:109,mrp:119,stock:45}]},
 {id:'p7',sku:'JWM-RTC-001',name:'Tandoori Chicken Tikka',category:'Ready to Cook',description:'Marinated boneless bites—pan-fry or air-fry in minutes.',weight:'300 g',servings:'2–3',price:239,mrp:279,stock:11,icon:'🔥',attributes:['boneless','skinless','marinated'],cutTypes:['tikka','boneless bites'],recommendation:'Pair with Chicken Breast Boneless',variants:[{weight:'250 g',price:209,mrp:239,stock:15},{weight:'500 g',price:389,mrp:439,stock:11},{weight:'1 kg',price:749,mrp:829,stock:5}]},
 {id:'p8',sku:'JWM-CMB-001',name:'Family Curry Combo',category:'Combos',description:'Chicken curry cut with farm-fresh eggs for family meals.',weight:'500 g + 6 eggs',servings:'4–5',price:249,mrp:298,stock:8,icon:'🛍️',attributes:['skinless'],cutTypes:['combo'],recommendation:'Best for a family dinner',variants:[{weight:'500 g + 6 eggs',price:249,mrp:298,stock:8},{weight:'1 kg + 12 eggs',price:469,mrp:549,stock:4}]}
];
export const CATEGORIES=['All','Chicken','Mutton','Fish & Seafood','Eggs','Ready to Cook','Combos'] as const;
export const SLOTS=['9:00–11:00 AM','12:00–3:00 PM','4:00–6:00 PM','7:00–9:00 PM'];
export const SERVICEABLE_PINS=['834002','834003','834004'];
