import React, { useState } from 'react';
import { ArrowLeft, Mail, UserRound, X } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { supabase } from '../supabase';

type Props = { open:boolean; user:User|null; onClose:()=>void; onSignedOut:()=>void };

export const AccountPanel: React.FC<Props> = ({open,user,onClose,onSignedOut}) => {
 const [email,setEmail]=useState(''); const [otp,setOtp]=useState(''); const [step,setStep]=useState<'email'|'otp'>('email');
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 if(!open)return null;
 const requestOtp=async(e:React.FormEvent)=>{e.preventDefault();const normalized=email.trim().toLowerCase();if(!normalized||!/^\S+@\S+\.\S+$/.test(normalized)){setError('Enter a valid email address.');return;}setBusy(true);setError('');setNotice('');const {error:sendError}=await supabase.auth.signInWithOtp({email:normalized,options:{shouldCreateUser:true}});setBusy(false);if(sendError){setError(sendError.message);return;}setEmail(normalized);setStep('otp');setNotice('We sent a 6-digit code to your email.');};
 const verifyOtp=async(e:React.FormEvent)=>{e.preventDefault();const token=otp.trim();if(!/^\d{6}$/.test(token)){setError('Enter the 6-digit code from your email.');return;}setBusy(true);setError('');const {error:verifyError}=await supabase.auth.verifyOtp({email,token,type:'email'});setBusy(false);if(verifyError){setError(verifyError.message);return;}setNotice('You are signed in.');setOtp('');};
 const signOut=async()=>{setBusy(true);setError('');const {error:signOutError}=await supabase.auth.signOut();setBusy(false);if(signOutError){setError(signOutError.message);return;}onSignedOut();};
 return <div className="account-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose();}}><section className="account-panel" role="dialog" aria-modal="true" aria-labelledby="account-title"><button className="account-close" onClick={onClose} aria-label="Close account"><X/></button><div className="account-icon"><UserRound/></div><span className="account-eyebrow">YOUR JABWEMEAT ACCOUNT</span><h2 id="account-title">{user?'Welcome back':'Sign in to continue'}</h2>{user?<><p className="account-email"><Mail/> {user.email}</p><p className="account-copy">Your account is ready for faster checkout and order updates.</p><button className="account-submit" onClick={signOut} disabled={busy}>{busy?'Signing out…':'Sign out'}</button></>:step==='email'?<form onSubmit={requestOtp}><p className="account-copy">Use your email to receive a secure one-time passcode. No password needed.</p><label>Email address<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" disabled={busy} /></label>{error&&<p className="account-error" role="alert">{error}</p>}{notice&&<p className="account-notice" role="status">{notice}</p>}<button className="account-submit" disabled={busy}>{busy?'Sending code…':'Send 6-digit code'}</button></form>:<form onSubmit={verifyOtp}><p className="account-copy">Enter the code sent to <b>{email}</b>.</p><label>6-digit code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="000000" disabled={busy} /></label>{error&&<p className="account-error" role="alert">{error}</p>}{notice&&<p className="account-notice" role="status">{notice}</p>}<button className="account-submit" disabled={busy}>{busy?'Verifying…':'Verify code'}</button><button type="button" className="account-back" onClick={()=>{setStep('email');setError('');setNotice('');}} disabled={busy}><ArrowLeft/> Use a different email</button></form>}</section></div>;
};
