import React, { useState } from 'react';
import { Package, ShoppingBag, IndianRupee, Users, Search, Plus, AlertTriangle, MoreHorizontal } from 'lucide-react';
import type { Product } from '../types';

type Props={products:Product[]; setProducts:React.Dispatch<React.SetStateAction<Product[]>>};
export const AdminDashboard: React.FC<Props> = ({products,setProducts}) => {
 const [query,setQuery]=useState(''); const filtered=products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase()));
 const adjust=(id:string,delta:number)=>setProducts(prev=>prev.map(p=>p.id===id?{...p,stock:Math.max(0,p.stock+delta)}:p));
 return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-secondary">OPERATIONS</p><h1 className="text-3xl font-black">Admin dashboard</h1><p className="text-sm text-base-content/60">Prototype data for storefront, inventory and order operations.</p></div><button className="btn btn-primary"><Plus size={18}/>Add product</button></div>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShoppingBag,'Live orders','12','4 need confirmation'],[IndianRupee,'COD value','₹8,420','Today'],[Package,'Active SKUs',String(products.length),`${products.filter(p=>p.stock<10).length} low stock`],[Users,'Customers','148','23 verified this week']].map(([Icon,label,value,note]:any)=><div className="card border border-base-300 bg-base-100" key={label}><div className="card-body p-5"><div className="flex items-center justify-between"><span className="text-sm text-base-content/60">{label}</span><Icon size={19} className="text-primary"/></div><div className="text-2xl font-black">{value}</div><div className="text-xs text-base-content/60">{note}</div></div></div>)}</div>
  <div className="grid gap-5 lg:grid-cols-[1.6fr_.8fr]">
   <section className="card border border-base-300 bg-base-100"><div className="card-body gap-4 p-0"><div className="flex flex-wrap items-center justify-between gap-3 p-5 pb-0"><div><h2 className="card-title">Inventory</h2><p className="text-sm text-base-content/60">Change stock instantly in this prototype.</p></div><label className="input input-bordered input-sm flex items-center gap-2"><Search size={14} className="opacity-60"/><input className="grow" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search SKU…"/></label></div><div className="overflow-x-auto"><table className="table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><div className="font-semibold">{p.name}</div><div className="text-xs text-base-content/50">{p.sku} · {p.weight}</div></td><td>₹{p.price}</td><td><div className="join"><button className="btn btn-xs join-item" onClick={()=>adjust(p.id,-1)}>−</button><span className="btn btn-xs join-item pointer-events-none">{p.stock}</span><button className="btn btn-xs join-item" onClick={()=>adjust(p.id,1)}>+</button></div></td><td><span className={`badge badge-sm ${p.stock===0?'badge-error':p.stock<10?'badge-warning':'badge-success'}`}>{p.stock===0?'Out':p.stock<10?'Low':'In stock'}</span></td><td><button className="btn btn-ghost btn-xs"><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></div></section>
   <aside className="space-y-5"><div className="card bg-secondary text-secondary-content"><div className="card-body"><h2 className="card-title">Order pipeline</h2>{[['New / unconfirmed',4],['Preparing',3],['Out for delivery',3],['Delivered',2]].map(([s,n]:any)=><div className="flex items-center justify-between rounded-xl bg-secondary-content/10 p-3" key={s}><span>{s}</span><span className="badge bg-base-100 text-base-content">{n}</span></div>)}</div></div><div className="alert alert-warning items-start"><AlertTriangle size={20}/><div><div className="font-bold">Low-stock attention</div><div className="text-sm">{products.filter(p=>p.stock<10).map(p=>p.name).join(', ')||'No low-stock products'}.</div></div></div><div className="card bg-base-200"><div className="card-body"><h3 className="font-bold">Coming in the full backend</h3><ul className="list-disc space-y-1 pl-4 text-sm text-base-content/60"><li>Products, images, SKUs and pricing</li><li>Orders, COD and invoices</li><li>Delivery slots and capacity</li><li>Abandoned-cart recovery</li><li>Customers and verification</li><li>WhatsApp activation controls</li></ul></div></div></aside>
  </div>
 </main>;
};
