import React,{useMemo,useState} from 'react';
import { ShieldCheck, Snowflake, BadgeIndianRupee, Truck, Search, ArrowRight, MapPin, Clock3, PackageCheck, ChevronRight, ShoppingCart } from 'lucide-react';
import { CATEGORIES } from '../data';
import { ProductCard } from './ProductCard';
import type { CartItem, Product, Language } from '../types';
const copy={en:{fish:'Bengali Fish Specials',mutton:'Bone-in mutton for slow, rich curries',cities:'Delivery messaging for Ranchi, Patna and Kolkata',festival:'Festival-ready favourites, planned around your kitchen',cod:'Cash on delivery available'},hi:{fish:'बंगला मछली स्पेशल',mutton:'धीमी आँच की करी के लिए हड्डी वाला मटन',cities:'रांची, पटना और कोलकाता में डिलीवरी',festival:'त्योहारों के लिए पसंदीदा विकल्प',cod:'कैश ऑन डिलीवरी उपलब्ध'},bn:{fish:'বাংলা মাছের স্পেশাল',mutton:'ধীরে রান্নার জন্য হাড়সহ মাটন',cities:'রাঁচি, পাটনা ও কলকাতায় ডেলিভারি',festival:'উৎসবের জন্য প্রস্তুত পছন্দ',cod:'ক্যাশ অন ডেলিভারি উপলব্ধ'}};
const categoryCopy:Record<string,Record<Language,string>>={'Chicken':{en:'Chicken',hi:'चिकन',bn:'চিকেন'},'Mutton':{en:'Mutton',hi:'मटन',bn:'মাটন'},'Fish & Seafood':{en:'Fish & Seafood',hi:'मछली और सीफूड',bn:'মাছ ও সি ফুড'},'Eggs':{en:'Eggs',hi:'अंडे',bn:'ডিম'},'Ready to Cook':{en:'Ready to Cook',hi:'रेडी टू कुक',bn:'রেডি টু কুক'},'Combos':{en:'Combos',hi:'कॉम्बो',bn:'কম্বো'},'All':{en:'All',hi:'सभी',bn:'সব'}};
const CATEGORY_IMAGES:Record<string,string>={'All':'assets/family-combo.webp','Chicken':'assets/chicken-curry.webp','Mutton':'assets/mutton.webp','Fish & Seafood':'assets/rohu.webp','Eggs':'assets/eggs.webp','Ready to Cook':'assets/tikka.webp','Combos':'assets/family-combo.webp'};
type Slot={id?:string;label:string};
type Props={language:Language;products:Product[];cart:CartItem[];category:string;setCategory:(v:string)=>void;search:string;setSearch:(v:string)=>void;pincode:string;serviceable:boolean;slots?:Slot[];onAdd:(p:Product)=>void;onRemove:(id:string)=>void;onCart:()=>void;subtotal:number;categories?:string[]};
export const Storefront:React.FC<Props>=({language,products,cart,category,setCategory,search,setSearch,pincode,serviceable,slots=[],onAdd,onRemove,onCart,subtotal,categories=CATEGORIES as unknown as string[]})=>{
 const categoryList=['All',...categories.filter(c=>c!=='All')];const [filters,setFilters]=useState<string[]>([]);const toggleFilter=(f:string)=>setFilters(x=>x.includes(f)?x.filter(v=>v!==f):[...x,f]);const filterOptions=['bone-in','boneless','skinless','marinated','curry cut','fillet','steaks','chops'];const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.description}`).toLowerCase().includes(search.toLowerCase())&&(filters.length===0||filters.some(f=>p.attributes?.includes(f)||p.cutTypes?.includes(f)))),[products,category,search,filters]);const explore=(c:string)=>{setCategory(c);requestAnimationFrame(()=>document.getElementById('shop')?.scrollIntoView({behavior:'smooth'}))};const nextSlot=slots.find(s=>s.label.trim());
 return <main id="top"><section className="hero-section"><img className="hero-bg" src="assets/hero-chicken.webp" alt="Fresh whole chicken with vegetables"/><div className="hero-overlay"/><div className="hero-inner"><div className="hero-copy"><span className="eyebrow">FRESHLY PREPARED IN RANCHI</span><h1>Premium cuts,<br/>delivered <em>fresh.</em></h1><p>Clean cuts. Careful packing. Dependable slot-based delivery from our kitchen to yours.</p><div className="hero-actions"><button className="primary-cta" onClick={()=>explore('All')}><span>SHOP ALL</span><ArrowRight size={17}/></button><div className="hero-category-options">{['Chicken','Mutton','Fish & Seafood','Ready to Cook'].map(c=><button key={c} onClick={()=>explore(c)}>{c}</button>)}</div></div><div className="hero-badges"><span><ShieldCheck/>Quality checked</span><span><Snowflake/>Chilled handling</span><span><PackageCheck/>Cleanly packed</span></div></div></div></section>
 <section className="quick-benefits" aria-label="JabWeMeat trust promises"><div className="quick-benefits-inner"><div><span className="benefit-icon"><ShieldCheck/></span><p><strong>QUALITY CHECKED</strong><small>Every cut inspected before packing</small></p></div><div><span className="benefit-icon"><Snowflake/></span><p><strong>CHILLED HANDLING</strong><small>Temperature-aware from kitchen to door</small></p></div><div><span className="benefit-icon"><PackageCheck/></span><p><strong>CLEANLY PACKED</strong><small>Sealed fresh for your delivery slot</small></p></div><div className="fssai-placeholder"><span className="benefit-icon"><BadgeIndianRupee/></span><p><strong>FSSAI DETAILS</strong><small>Registration information coming soon</small></p></div></div></section>
 <section className="store-container" id="shop"><div className={`service-banner ${serviceable?'available':'unavailable'}`}><span><MapPin/></span><div><strong>{serviceable?`Delivering to ${pincode}`:`We’re not at ${pincode} yet`}</strong><small>{serviceable?'Choose from today’s available delivery slots.':'Currently serving 834002, 834003 and 834004.'}</small></div><button>CHANGE PIN <ChevronRight/></button></div>
  <div className="delivery-confidence" aria-label="Delivery availability"><div><Clock3/><span><b>Next available slot</b><small>{serviceable&&nextSlot?nextSlot.label:'Unavailable — live slots not configured'}</small></span></div><div><b>Order cutoff</b><small>Unavailable — no cutoff configured</small></div></div>
  <label className="mobile-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search fresh products…"/></label><div className="section-heading centered"><span>EXPLORE OUR RANGE</span><h2>Shop by category</h2><i/></div><div className="category-strip">{categoryList.map(c=><button key={c} className={category===c?'selected':''} onClick={()=>setCategory(c)}><img src={CATEGORY_IMAGES[c]||'assets/family-combo.webp'} alt=""/><span/><b>{c==='All'?'All Products':c}</b><small>SHOP NOW</small></button>)}</div><div className="section-heading centered products-heading"><span>FRESH PICKS</span><h2>{category==='All'?'Our best sellers':category}</h2><i/></div><div className="discovery-toolbar"><div className="filter-heading"><strong>Filter cuts</strong><small>{filtered.length} products</small></div><div className="filter-options">{filterOptions.map(f=><button key={f} className={filters.includes(f)?'selected':''} onClick={()=>toggleFilter(f)}>{f}</button>)}</div>{filters.length>0&&<button className="clear-filters" onClick={()=>setFilters([])}>Clear filters</button>}</div>{filtered.length?<div className="product-grid">{filtered.map(p=><ProductCard key={p.id} language={language} product={p} quantity={cart.find(i=>i.id===p.id)?.quantity||0} onAdd={()=>onAdd(p)} onRemove={()=>onRemove(p.id)}/>)}</div>:<div className="empty-products"><Search/><h3>No matching products</h3><p>Try another search or category.</p></div>}</section>
 <section className="regional-rails" aria-label="Regional storefront highlights"><div><b>{copy[language].fish}</b><span>Freshness-led regional picks</span></div><div><b>{copy[language].mutton}</b><span>Ask about current catalogue selection</span></div><div><b>{copy[language].cities}</b><span>Service areas are confirmed by PIN code</span></div><div><b>{copy[language].festival}</b><span>Seasonal content without date promises</span></div></section><section className="launch-offer"><div><span>WELCOME TO JABWEMEAT™</span><h2>₹100 off your very first order</h2><p>Discover better freshness without paying a third-party marketing premium.</p></div><div><b>₹100</b><small>FIRST ORDER<br/>SAVINGS</small></div></section><section className="promise-section"><div className="promise-inner"><div className="local-trust"><strong>{copy[language].cod}</strong><p>Local kitchen team, careful preparation and clear slot-based ordering. Availability and delivery are always confirmed at checkout.</p></div><div className="promise-title"><span>OUR PROMISE</span><h2>Quality you can see.<br/>Freshness you can taste.</h2><p>Our process is built around careful sourcing, hygienic preparation, chilled handling and transparent value.</p></div><div className="promise-grid">{[[ShieldCheck,'Hygiene first','Clean preparation and careful handling at every step.'],[Snowflake,'Chilled, not frozen','Temperature-aware packing through dispatch.'],[Clock3,'Your delivery window','Configured slots are confirmed at checkout.'],[Truck,'Ranchi focused','Local service across selected PIN codes.']].map(([Icon,title,body]:any)=><div className="promise-card" key={title}><span><Icon/></span><div><h3>{title}</h3><p>{body}</p></div></div>)}</div></div></section>{cart.length>0&&<div className="floating-cart-summary"><div><ShoppingCart/><span><b>{cart.reduce((n,i)=>n+i.quantity,0)} item{cart.reduce((n,i)=>n+i.quantity,0)===1?'':'s'} in cart</b><small>Subtotal ₹{subtotal}</small></span></div><button onClick={onCart}>Review cart <ArrowRight/></button></div>}</main>;
};
