-- Phase 2: cancellations, refunds, proof of delivery, COD collection and notifications.
alter table public.orders add column if not exists cancellation_reason text;
alter table public.orders add column if not exists cancelled_at timestamptz;
create table if not exists public.refund_requests (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, amount numeric(10,2) not null check(amount>=0), reason text not null, status text not null default 'Requested' check(status in ('Requested','Approved','Processing','Completed','Rejected')), requested_by uuid references auth.users(id) on delete set null, requested_by_email text, processed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(order_id));
create table if not exists public.delivery_proofs (order_id uuid primary key references public.orders(id) on delete cascade, delivered_at timestamptz, recipient_name text, proof_url text, notes text, cod_collected numeric(10,2) check(cod_collected is null or cod_collected>=0), cod_collected_at timestamptz, recorded_by uuid references auth.users(id) on delete set null, recorded_by_email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.customer_notification_events (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, channel text not null default 'email' check(channel in ('email','sms','whatsapp')), event_type text not null, recipient text, status text not null default 'queued' check(status in ('queued','sent','failed')), provider_id text, error text, created_at timestamptz not null default now());
create index if not exists refund_requests_status_idx on public.refund_requests(status); create index if not exists notification_events_order_idx on public.customer_notification_events(order_id,created_at desc);
create or replace function public.request_order_refund(p_order_id uuid,p_amount numeric,p_reason text) returns public.refund_requests language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.refund_requests; begin if auth.uid() is null or not public.has_role_permission('Orders','Edit') then raise exception 'Orders Edit permission is required'; end if; if p_amount<=0 or nullif(btrim(p_reason),'') is null then raise exception 'Refund amount and reason are required'; end if; insert into public.refund_requests(order_id,amount,reason,requested_by,requested_by_email) values(p_order_id,p_amount,btrim(p_reason),auth.uid(),lower(coalesce(auth.jwt()->>'email',''))) on conflict(order_id) do update set amount=excluded.amount,reason=excluded.reason,status='Requested',requested_by=excluded.requested_by,requested_by_email=excluded.requested_by_email returning * into r; return r; end; $$;
create or replace function public.record_delivery_proof(p_order_id uuid,p_recipient_name text,p_proof_url text,p_notes text,p_cod_collected numeric) returns public.delivery_proofs language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.delivery_proofs; begin if auth.uid() is null or not public.has_role_permission('Orders','Edit') then raise exception 'Orders Edit permission is required'; end if; insert into public.delivery_proofs(order_id,delivered_at,recipient_name,proof_url,notes,cod_collected,cod_collected_at,recorded_by,recorded_by_email) values(p_order_id,now(),nullif(btrim(p_recipient_name),''),nullif(btrim(p_proof_url),''),nullif(btrim(p_notes),''),p_cod_collected,case when p_cod_collected is not null then now() end,auth.uid(),lower(coalesce(auth.jwt()->>'email',''))) on conflict(order_id) do update set delivered_at=excluded.delivered_at,recipient_name=excluded.recipient_name,proof_url=excluded.proof_url,notes=excluded.notes,cod_collected=excluded.cod_collected,cod_collected_at=excluded.cod_collected_at,recorded_by=excluded.recorded_by,recorded_by_email=excluded.recorded_by_email returning * into r; return r; end; $$;
revoke all on function public.request_order_refund(uuid,numeric,text) from public,anon; revoke all on function public.record_delivery_proof(uuid,text,text,text,numeric) from public,anon; grant execute on function public.request_order_refund(uuid,numeric,text) to authenticated; grant execute on function public.record_delivery_proof(uuid,text,text,text,numeric) to authenticated;
alter table public.refund_requests enable row level security; alter table public.delivery_proofs enable row level security; alter table public.customer_notification_events enable row level security;
drop policy if exists "orders readers view refunds" on public.refund_requests; drop policy if exists "orders readers view proofs" on public.delivery_proofs; drop policy if exists "orders readers view notifications" on public.customer_notification_events;
create policy "orders readers view refunds" on public.refund_requests for select to authenticated using(public.has_role_permission('Orders','View')); create policy "orders readers view proofs" on public.delivery_proofs for select to authenticated using(public.has_role_permission('Orders','View')); create policy "orders readers view notifications" on public.customer_notification_events for select to authenticated using(public.has_role_permission('Orders','View'));
